名字: 名称:每日更新

在:
日程安排:
    - 时间单位: '55 0 */2 * *'- cron# 每2天凌晨00点55分执行任务（上海时区的协调世界时。亦称COORDINATED UNIVERSAL TIME时间)'55 0 */2 * *' #每2天凌晨00点55分执行任务（上海时区的协调世界时。亦称COORDINATED UNIVERSAL TIME时间)# 每2天凌晨00点55分执行任务（上海时区的UTC时间）
工作流_调度:  # 允许手动触发工作流

工作:
运行脚本:
连续运行: 运行# 使用最新的人的本质运行器Ubuntu-最新#使用最新的人的本质运行器# 使用最新的Ubuntu运行器

步伐:
    - 名字: -名称:签出存储库#检出代码库# 检出代码库
使用: 用法:actions/checkout@v3

    - 名字: -名称# 设置计算机编程语言环境设置Python #设置计算机编程语言环境# 设置Python环境
使用: 用法:操作/设置-python@v4
随着:
python版本: '3.10'python版本# 使用Python 3.10“3.10”#使用Python 3.10# 使用Python 3.10

    - 名字: - name# 缓存点依赖项缓存依赖项#缓存点依赖项# 缓存pip依赖项
使用: 用途:actions/cache@v4
随着:
小路: 路径:~/。缓存/画中画
键: key:$ { { runner . OS } }-pip-$ { **/requirements.txt ' hashFiles(' * */requirements . txt ')} }{{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
还原键: |
${{ runner.os }}-pip-

    - 名字: -名称:安装系统依赖项#安装系统依赖# 安装系统依赖
奔跑: |
sudo apt-get更新
sudo apt-get install -y ffmpeg

    - 名字: - name# 安装计算机编程语言依赖安装Python依赖项#安装计算机编程语言依赖# 安装Python依赖
奔跑: |
python -m pip安装-升级pip
pip安装请求

    - 名字: -名称:运行Python脚本#执行主脚本# 执行主脚本
奔跑: |
python main.py

    - 名字: - name:如果更改，提交并推送#如果有更改,则提交并推送# 如果有更改，则提交并推送
奔跑: |
git config-local user . email "772109739@qq.com"
git config -本地user.name "沧海笑"
git add -A
如果！git diff-staged-quiet；然后
git commit -m "自动更新实时文件"
git pull - rebase
git推送
船方不负担装货费用

包封/包围（动词envelop的简写）:
坦桑尼亚: TZ:亚洲/上海#设置时区为上海# 设置时区为上海
